name: Deploy Jupyter Book to GitHub Pages

on:
  # For now we just use manual trigger.
  push:
    branches: ["main", "doc"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# Build the landing page and jupyter book, integrate those pages and deploy those pages to GitHub Pages separately.
jobs:
  build-jupyter-book:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [en, ja]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Set up uv.
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      # Set up Python with uv.
      - name: Set up Python with uv
        run: uv python install 3.10
      # Install all dependencies using uv.
      - name: uv Install
        shell: bash
        run:  |
          set -eux
          uv sync --group docs
      # Build the jupyter notebooks.
      - name: Build the book and LP
        run: |
          cd docs
          uv run jupyter-book build ${{ matrix.lang }}
          cd ..
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: doc-jupyter-book-${{ matrix.lang }}
          path: 'docs/${{ matrix.lang }}/_build/html'
  
  integrate-pages:
    needs: [build-jupyter-book]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create unified site structure
        run: |
          mkdir -p docs/_build/html
          mkdir -p docs/_build/html/en && cp -r doc-jupyter-book-en/* docs/_build/html/en/
          mkdir -p docs/_build/html/ja && cp -r doc-jupyter-book-ja/* docs/_build/html/ja/
          cp -r docs/_build/html/en/index.html docs/_build/html/index.html
      # Upload the unified site structure as a single artifact.
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: doc-jupyter-book
          path: 'docs/_build/html'

  # deploy:
  #   needs: [build-jupyter-book, integrate-pages]
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download all artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: doc-jupyter-book
  #         path: .
  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v3
  #       with:
  #         path: "."
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4